### ISSUE TITLE
failed so solve error: error getting credentials

### ISSUE THREAD

**Issue by antonengelhardt** [bobuhiro11/containerized-devstack#9] opened 2023-03-11 18:08 UTC
Hey @bobuhiro11. 

First, thanks for this repo. I find it really hard to install devstack currently. 

When running `sudo docker-compose up -d` (as in Readme) i get the following error:

```
[+] Building 0.6s (6/7)
[+] Building 0.6s (7/7) FINISHED
 => [containerized-devstack-controller internal] load build definition from Dockerfile                                  0.0s
 => => transferring dockerfile: 69B                                                                                     0.0s
 => [containerized-devstack-compute-1 internal] load build definition from Dockerfile                                   0.0s
 => => transferring dockerfile: 69B                                                                                     0.0s
 => [containerized-devstack-compute-2 internal] load build definition from Dockerfile                                   0.0s
 => => transferring dockerfile: 69B                                                                                     0.0s
 => [containerized-devstack-controller internal] load .dockerignore                                                     0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [containerized-devstack-compute-1 internal] load .dockerignore                                                      0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [containerized-devstack-compute-2 internal] load .dockerignore                                                      0.0s
 => => transferring context: 2B                                                                                         0.0s
 => ERROR [containerized-devstack-compute-1 internal] load metadata for docker.io/library/ubuntu:20.04                  0.5s
------
 > [containerized-devstack-compute-1 internal] load metadata for docker.io/library/ubuntu:20.04:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: ``
```

Can you help me with this? 

Thanks in advance.

**Comment by bobuhiro11** [comment] 2023-03-12 07:50
Hi @antonengelhardt ,

Hmm, from the logs, I think it is caused by the pull of the container image. Does the following command succeed? If it fails, I guess you better look at your docker configuration first.

This is the first time I am encountering this error, so I am not sure.

```bash
$ sudo docker pull ubuntu:20.04
```

**Comment by antonengelhardt** [comment] 2023-03-12 08:15
Thanks for your fast reply, @bobuhiro11 .

The pull succeeds. Sidenote: I am on M1... 

Do you have any other ideas?

**Comment by bobuhiro11** [comment] 2023-03-12 08:57
OK. Sorry, my guess was wrong.
I have only tested this on x64 Linux.
And devstack probably doesn't work on M1 now,  so I would recommend running it in an x64 Linux.

**Comment by antonengelhardt** [comment] 2023-03-13 17:49
> OK. Sorry, my guess was wrong.
> 
> I have only tested this on x64 Linux.
> 
> And devstack probably doesn't work on M1 now,  so I would recommend running it in an x64 Linux.

Thanks ok. I just manually installed devstack on a Linux Vm now 

The weird thing is that I can run an Ubuntu container without any issues

**Comment by bobuhiro11** [comment] 2023-03-14 01:21
I'll close this issue since devstack seems to have worked fine.

> The weird thing is that I can run an Ubuntu container without any issues

Devstack depends on many OpenStack components and virtualization technologies, some of which probably do not support M1. Even if Ubuntu works on M1.

**Closed as completed by bobuhiro11** 2023-03-14 01:21 UTC
